version: "3"

services:

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 80:80

  flask:
    container_name: flask
    env_file:
      - database/database.conf
    build: ./flask
    restart: always
    environment:
      - APP_NAME=RateMyMolecule
      - FLASK_ENV=production
      - SECRET_KEY=9b10048d11e1481ab6c7deb9b58c3467
    expose:
      - 8080

  database:
    container_name: database
    env_file:
      - database/database.conf
    build: ./database
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
